# Generated by Django 3.2.23 on 2023-12-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='image',
            field=models.FileField(upload_to='customer-enqiries'),
        ),
    ]
