# Generated by Django 3.2.23 on 2023-12-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.review'),
        ),
    ]
